version: "3.8"
services:
  scylla:
    image: scylladb/scylla
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --connect-timeout 5"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla

  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mostvaluableship -d julia"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: mostvaluableship
      POSTGRES_PASSWORD: friendship
      POSTGRES_DB: julia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pulsar:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  julia-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REBUILD: 1
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  picafe-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REBUILD: 1
    ports:
      - "4000:4000"
    depends_on:
      scylla:
        condition: service_healthy
      pulsar:
        condition: service_started

volumes:
  postgres_data:
  scylla_data:
