version: "3.8"
services:
  scylla:
    image: scylladb/scylla
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --connect-timeout 5"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9042:9042"

  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mostvaluableship"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: mostvaluableship
      POSTGRES_PASSWORD: friendship
      POSTGRES_DB: julia
    ports:
      - "5432:5432"
